// <auto-generated />
using System;
using DailyBreadApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyBreadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112225611_AddCompletedHabits")]
    partial class AddCompletedHabits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyBreadApi.Models.CompletedHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<int>("PresetHabitid")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PresetHabitid");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.PresetHabit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PresetHabits");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Spend some time in prayer",
                            icon = "none",
                            title = "Pray"
                        },
                        new
                        {
                            id = 2,
                            description = "Find a good devotional and commit to doing one a day",
                            icon = "none",
                            title = "Daily Devotional"
                        },
                        new
                        {
                            id = 3,
                            description = "Read one chapter out of the Bible",
                            icon = "none",
                            title = "A Chapter A Day"
                        },
                        new
                        {
                            id = 4,
                            description = "Memorize one verse from anywhere in the bible",
                            icon = "none",
                            title = "Memorize A Verse"
                        },
                        new
                        {
                            id = 5,
                            description = "Find a sermon to listen to",
                            icon = "none",
                            title = "Listen To A Sermon"
                        },
                        new
                        {
                            id = 6,
                            description = "Spend some time in worship whether through song or adoration in prayer",
                            icon = "none",
                            title = "Worship"
                        },
                        new
                        {
                            id = 7,
                            description = "Dedicate some time to fasting from someting (Food, Social Media, TV, etc.)",
                            icon = "none",
                            title = "Fast"
                        },
                        new
                        {
                            id = 8,
                            description = "Reflect on your relationship with God and journal what comes to mind",
                            icon = "none",
                            title = "Spiritual Journaling"
                        },
                        new
                        {
                            id = 9,
                            description = "Check in with a brother or sister in the faith about something you wish to be held acountable for",
                            icon = "none",
                            title = "Accountability"
                        },
                        new
                        {
                            id = 10,
                            description = "Reach out to a brother or sister in the faith and lift them up with encouraging words",
                            icon = "none",
                            title = "Exhortation"
                        },
                        new
                        {
                            id = 11,
                            description = "Through a passage of scripture, a sermon, or a lecture take some notes",
                            icon = "none",
                            title = "Study Time"
                        },
                        new
                        {
                            id = 12,
                            description = "Listen to an episode of a podcast",
                            icon = "none",
                            title = "Podcast"
                        },
                        new
                        {
                            id = 13,
                            description = "Reflect on your life and journal what comes to mind",
                            icon = "none",
                            title = "Mental Health Journaling"
                        },
                        new
                        {
                            id = 14,
                            description = "Read one chapter of a book",
                            icon = "none",
                            title = "Read A Book"
                        },
                        new
                        {
                            id = 15,
                            description = "List out what needs to get done today and cross off the list as you go about your day",
                            icon = "none",
                            title = "Create A To-Do List"
                        },
                        new
                        {
                            id = 16,
                            description = "Set at least one hour of your day as a time without your phone in sight",
                            icon = "none",
                            title = "No Phone"
                        },
                        new
                        {
                            id = 17,
                            description = "Spend some time stretching or focusing your breathing",
                            icon = "none",
                            title = "Stretching + Breathing Exercises"
                        },
                        new
                        {
                            id = 18,
                            description = "Complete on brain puzzle (Sudoku, CrossWord, Wordle, etc.)",
                            icon = "none",
                            title = "Complete A Brain Puzzle"
                        },
                        new
                        {
                            id = 19,
                            description = "Find something around your house or work to clean up",
                            icon = "none",
                            title = "Clean"
                        },
                        new
                        {
                            id = 20,
                            description = "Make your bed in the morning",
                            icon = "none",
                            title = "Make Your Bed"
                        },
                        new
                        {
                            id = 21,
                            description = "Spend 15 minutes learning a new skill",
                            icon = "none",
                            title = "Learn Something New"
                        },
                        new
                        {
                            id = 22,
                            description = "Drink at least two bottles of water (1 Liter)",
                            icon = "none",
                            title = "Drink Water"
                        },
                        new
                        {
                            id = 23,
                            description = "Hit 3,000 steps",
                            icon = "none",
                            title = "Daily Steps"
                        },
                        new
                        {
                            id = 24,
                            description = "Spend at least 30 minutes working out",
                            icon = "none",
                            title = "Workout"
                        },
                        new
                        {
                            id = 25,
                            description = "Eat one healthy meal",
                            icon = "none",
                            title = "Eat Healthy"
                        },
                        new
                        {
                            id = 26,
                            description = "Go to bed by a set time",
                            icon = "none",
                            title = "Bedtime"
                        },
                        new
                        {
                            id = 27,
                            description = "Wake up by a set time",
                            icon = "none",
                            title = "Wake Up"
                        });
                });

            modelBuilder.Entity("DailyBreadApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DailyBreadApi.Models.UserHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "HabitId")
                        .IsUnique();

                    b.ToTable("UserHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.CompletedHabit", b =>
                {
                    b.HasOne("DailyBreadApi.Models.PresetHabit", "PresetHabit")
                        .WithMany()
                        .HasForeignKey("PresetHabitid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyBreadApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresetHabit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DailyBreadApi.Models.UserHabit", b =>
                {
                    b.HasOne("DailyBreadApi.Models.PresetHabit", "PresetHabit")
                        .WithMany("UserHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyBreadApi.Models.User", "User")
                        .WithMany("UserHabits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresetHabit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DailyBreadApi.Models.PresetHabit", b =>
                {
                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.User", b =>
                {
                    b.Navigation("UserHabits");
                });
#pragma warning restore 612, 618
        }
    }
}
