// <auto-generated />
using System;
using DailyBreadApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyBreadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126234226_RenamePresetHabitId")]
    partial class RenamePresetHabitId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyBreadApi.Models.CompletedHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CompletedHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.PresetHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PresetHabits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spend some time in prayer",
                            Icon = "none",
                            Title = "Pray"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Find a good devotional and commit to doing one a day",
                            Icon = "none",
                            Title = "Daily Devotional"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Read one chapter out of the Bible",
                            Icon = "none",
                            Title = "A Chapter A Day"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Memorize one verse from anywhere in the bible",
                            Icon = "none",
                            Title = "Memorize A Verse"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Find a sermon to listen to",
                            Icon = "none",
                            Title = "Listen To A Sermon"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spend some time in worship whether through song or adoration in prayer",
                            Icon = "none",
                            Title = "Worship"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dedicate some time to fasting from someting (Food, Social Media, TV, etc.)",
                            Icon = "none",
                            Title = "Fast"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reflect on your relationship with God and journal what comes to mind",
                            Icon = "none",
                            Title = "Spiritual Journaling"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Check in with a brother or sister in the faith about something you wish to be held acountable for",
                            Icon = "none",
                            Title = "Accountability"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Reach out to a brother or sister in the faith and lift them up with encouraging words",
                            Icon = "none",
                            Title = "Exhortation"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Through a passage of scripture, a sermon, or a lecture take some notes",
                            Icon = "none",
                            Title = "Study Time"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Listen to an episode of a podcast",
                            Icon = "none",
                            Title = "Podcast"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Reflect on your life and journal what comes to mind",
                            Icon = "none",
                            Title = "Mental Health Journaling"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Read one chapter of a book",
                            Icon = "none",
                            Title = "Read A Book"
                        },
                        new
                        {
                            Id = 15,
                            Description = "List out what needs to get done today and cross off the list as you go about your day",
                            Icon = "none",
                            Title = "Create A To-Do List"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Set at least one hour of your day as a time without your phone in sight",
                            Icon = "none",
                            Title = "No Phone"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Spend some time stretching or focusing your breathing",
                            Icon = "none",
                            Title = "Stretching + Breathing Exercises"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Complete on brain puzzle (Sudoku, CrossWord, Wordle, etc.)",
                            Icon = "none",
                            Title = "Complete A Brain Puzzle"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Find something around your house or work to clean up",
                            Icon = "none",
                            Title = "Clean"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Make your bed in the morning",
                            Icon = "none",
                            Title = "Make Your Bed"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Spend 15 minutes learning a new skill",
                            Icon = "none",
                            Title = "Learn Something New"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Drink at least two bottles of water (1 Liter)",
                            Icon = "none",
                            Title = "Drink Water"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Hit 3,000 steps",
                            Icon = "none",
                            Title = "Daily Steps"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Spend at least 30 minutes working out",
                            Icon = "none",
                            Title = "Workout"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Eat one healthy meal",
                            Icon = "none",
                            Title = "Eat Healthy"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Go to bed by a set time",
                            Icon = "none",
                            Title = "Bedtime"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Wake up by a set time",
                            Icon = "none",
                            Title = "Wake Up"
                        });
                });

            modelBuilder.Entity("DailyBreadApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DailyBreadApi.Models.UserHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "HabitId")
                        .IsUnique();

                    b.ToTable("UserHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.UserHabit", b =>
                {
                    b.HasOne("DailyBreadApi.Models.PresetHabit", "PresetHabit")
                        .WithMany("UserHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyBreadApi.Models.User", "User")
                        .WithMany("UserHabits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresetHabit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DailyBreadApi.Models.PresetHabit", b =>
                {
                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("DailyBreadApi.Models.User", b =>
                {
                    b.Navigation("UserHabits");
                });
#pragma warning restore 612, 618
        }
    }
}
